In [126]:
import numpy as np
import pandas as pd
from datetime import datetime

In [140]:
import warnings

# Suppress future warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Activity Inference Data
0: Stationary

1: Walking

2: Running

3: Unknown

In [127]:
ActivityData = pd.DataFrame()
ActivityData = pd.read_csv('dataset/dataset/sensing/activity/activity_u00.csv')
ActivityData['userId'] = '00'
print(ActivityData)

         timestamp   activity inference userId
0       1364356801                    0     00
1       1364356804                    0     00
2       1364356807                    0     00
3       1364356809                    0     00
4       1364356992                    0     00
...            ...                  ...    ...
461986  1370048602                    0     00
461987  1370048605                    0     00
461988  1370048608                    3     00
461989  1370048610                    3     00
461990  1370048613                    3     00

[461991 rows x 3 columns]

In [128]:
ActivityData['timestamp'] = pd.to_datetime(ActivityData['timestamp'], unit = 's')
print(ActivityData)

                 timestamp   activity inference userId
0      2013-03-27 04:00:01                    0     00
1      2013-03-27 04:00:04                    0     00
2      2013-03-27 04:00:07                    0     00
3      2013-03-27 04:00:09                    0     00
4      2013-03-27 04:03:12                    0     00
...                    ...                  ...    ...
461986 2013-06-01 01:03:22                    0     00
461987 2013-06-01 01:03:25                    0     00
461988 2013-06-01 01:03:28                    3     00
461989 2013-06-01 01:03:30                    3     00
461990 2013-06-01 01:03:33                    3     00

[461991 rows x 3 columns]

In [129]:
ActivityData.rename(columns={' activity inference': 'activityInference'}, inplace=True)

In [130]:
ActivityData['date'] = ActivityData['timestamp'].dt.date
ActivityData['time'] = ActivityData['timestamp'].dt.time

In [131]:
print(ActivityData)

                 timestamp  activityInference userId        date      time
0      2013-03-27 04:00:01                  0     00  2013-03-27  04:00:01
1      2013-03-27 04:00:04                  0     00  2013-03-27  04:00:04
2      2013-03-27 04:00:07                  0     00  2013-03-27  04:00:07
3      2013-03-27 04:00:09                  0     00  2013-03-27  04:00:09
4      2013-03-27 04:03:12                  0     00  2013-03-27  04:03:12
...                    ...                ...    ...         ...       ...
461986 2013-06-01 01:03:22                  0     00  2013-06-01  01:03:22
461987 2013-06-01 01:03:25                  0     00  2013-06-01  01:03:25
461988 2013-06-01 01:03:28                  3     00  2013-06-01  01:03:28
461989 2013-06-01 01:03:30                  3     00  2013-06-01  01:03:30
461990 2013-06-01 01:03:33                  3     00  2013-06-01  01:03:33

[461991 rows x 5 columns]

In [132]:
ActivityData['date'] = pd.to_datetime(ActivityData['date'])
ActivityData['week'] = ActivityData['date'].dt.isocalendar().week
print(ActivityData['week'])

0         13
1         13
2         13
3         13
4         13
          ..
461986    22
461987    22
461988    22
461989    22
461990    22
Name: week, Length: 461991, dtype: UInt32

In [133]:
print(ActivityData['week'].unique())
print(ActivityData)

<IntegerArray>
[13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
Length: 10, dtype: UInt32
                 timestamp  activityInference userId       date      time  \
0      2013-03-27 04:00:01                  0     00 2013-03-27  04:00:01
1      2013-03-27 04:00:04                  0     00 2013-03-27  04:00:04
2      2013-03-27 04:00:07                  0     00 2013-03-27  04:00:07
3      2013-03-27 04:00:09                  0     00 2013-03-27  04:00:09
4      2013-03-27 04:03:12                  0     00 2013-03-27  04:03:12
...                    ...                ...    ...        ...       ...
461986 2013-06-01 01:03:22                  0     00 2013-06-01  01:03:22
461987 2013-06-01 01:03:25                  0     00 2013-06-01  01:03:25
461988 2013-06-01 01:03:28                  3     00 2013-06-01  01:03:28
461989 2013-06-01 01:03:30                  3     00 2013-06-01  01:03:30
461990 2013-06-01 01:03:33                  3     00 2013-06-01  01:03:33

        week
0         13
1         13
2         13
3         13
4         13
...      ...
461986    22
461987    22
461988    22
461989    22
461990    22

[461991 rows x 6 columns]

In [134]:
# print(ActivityData['activityInference'].unique())
count_of_3 = ActivityData['activityInference'].value_counts().get(3, 0)
count_of_0 = ActivityData['activityInference'].value_counts().get(0, 0)
count_of_1 = ActivityData['activityInference'].value_counts().get(1, 0)
count_of_2 = ActivityData['activityInference'].value_counts().get(2, 0)
print("Count of '0':", count_of_0)
print("Count of '1':", count_of_1)
print("Count of '2':", count_of_2)
print("Count of '3':", count_of_3)

Count of '0': 403461
Count of '1': 30659
Count of '2': 8990
Count of '3': 18881

In [135]:
# Convert 'time' column to datetime format
ActivityData['hour'] = ActivityData['timestamp'].dt.hour
# print(ActivityData)

bins = [-1, 6, 12, 18, 24]
labels = ['Early Morning', 'Morning', 'Afternoon', 'Evening']
ActivityData['timeCategory'] = pd.cut(ActivityData['hour'], bins=bins, labels=labels, right=False)
ActivityData.drop(columns=['hour'], inplace=True)

print(ActivityData)

                 timestamp  activityInference userId       date      time  \
0      2013-03-27 04:00:01                  0     00 2013-03-27  04:00:01
1      2013-03-27 04:00:04                  0     00 2013-03-27  04:00:04
2      2013-03-27 04:00:07                  0     00 2013-03-27  04:00:07
3      2013-03-27 04:00:09                  0     00 2013-03-27  04:00:09
4      2013-03-27 04:03:12                  0     00 2013-03-27  04:03:12
...                    ...                ...    ...        ...       ...
461986 2013-06-01 01:03:22                  0     00 2013-06-01  01:03:22
461987 2013-06-01 01:03:25                  0     00 2013-06-01  01:03:25
461988 2013-06-01 01:03:28                  3     00 2013-06-01  01:03:28
461989 2013-06-01 01:03:30                  3     00 2013-06-01  01:03:30
461990 2013-06-01 01:03:33                  3     00 2013-06-01  01:03:33

        week   timeCategory
0         13  Early Morning
1         13  Early Morning
2         13  Early Morning
3         13  Early Morning
4         13  Early Morning
...      ...            ...
461986    22  Early Morning
461987    22  Early Morning
461988    22  Early Morning
461989    22  Early Morning
461990    22  Early Morning

[461991 rows x 7 columns]

In [142]:
weeks = ActivityData['week'].unique()
# print(weeks)
# print(len(weeks))
# print(weeks[9])
dfs = []

for week in weeks[:-1]:
    twoWeekData = ActivityData[(ActivityData['week'] == week) | (ActivityData['week'] == week+1)]
    # print(twoWeekData['week'].unique())
    grouped = twoWeekData.groupby(['userId','timeCategory', 'activityInference']).size().reset_index(name='count')
    # print(grouped)
    # Pivot the grouped DataFrame
    pivot_df = grouped.pivot_table(index='userId', columns=['timeCategory', 'activityInference'], values='count').fillna(0)

    #  Concatenate 'timeCategory' and 'activityInference' to create column names
    pivot_df.columns = [f"{category}{inference}" for category, inference in pivot_df.columns]

    # Reset index to make 'userId' a column
    pivot_df.reset_index(inplace=True)
    dfs.append(pivot_df)

result_df = pd.concat(dfs)
result_df.reset_index(inplace=True)
result_df = result_df.drop(columns=['index'])

print(result_df)

   index userId  Early Morning0  Early Morning1  Early Morning2  \
0      0     00         21381.0           709.0           225.0
1      0     00         27565.0           357.0           200.0
2      0     00         26506.0           202.0           210.0
3      0     00         24494.0           477.0           259.0
4      0     00         24127.0           573.0           102.0
5      0     00         24687.0           428.0            43.0
6      0     00         24726.0           382.0            52.0
7      0     00         19653.0           276.0            32.0
8      0     00         16399.0           255.0            28.0

   Early Morning3  Morning0  Morning1  Morning2  Morning3  Afternoon0  \
0           560.0   21806.0     419.0      25.0     419.0     18534.0
1           406.0   28130.0     406.0      34.0     384.0     24312.0
2           407.0   28354.0     268.0      25.0     280.0     23981.0
3           764.0   26175.0     276.0      13.0     351.0     23782.0
4           654.0   21835.0    1926.0     205.0     659.0     18440.0
5           775.0   21936.0    2639.0     600.0     617.0     16937.0
6           742.0   21958.0    1096.0     408.0     406.0     18042.0
7           380.0   16244.0     233.0      11.0     236.0     15698.0
8           345.0   13146.0      84.0      17.0      77.0     14643.0

   Afternoon1  Afternoon2  Afternoon3  Evening0  Evening1  Evening2  Evening3
0      2020.0       913.0       481.0   17643.0    2940.0    1527.0    1214.0
1      2182.0       461.0       672.0   21319.0    2694.0    1696.0    1628.0
2      2481.0       527.0       844.0   20880.0    2807.0    1089.0    2623.0
3      2530.0       816.0       773.0   19879.0    2797.0    1349.0    2457.0
4      3223.0       963.0       736.0   18889.0    2514.0    1044.0    1526.0
5      3890.0       725.0      1463.0   20367.0    2459.0     292.0    1874.0
6      2505.0       361.0      2093.0   19718.0    2657.0     305.0    2430.0
7      1279.0        91.0      1968.0   13722.0    2358.0     251.0    1849.0
8      1353.0       619.0      1272.0   12453.0    2245.0     345.0    1113.0

## Exploration

In [136]:
print(ActivityData['timeCategory'])
category_counts = ActivityData['timeCategory'].value_counts()

print(category_counts)

0         Early Morning
1         Early Morning
2         Early Morning
3         Early Morning
4         Early Morning
              ...
461986    Early Morning
461987    Early Morning
461988    Early Morning
461989    Early Morning
461990    Early Morning
Name: timeCategory, Length: 461991, dtype: category
Categories (4, object): ['Early Morning' < 'Morning' < 'Afternoon' < 'Evening']
timeCategory
Early Morning    118585
Evening          115962
Afternoon        114031
Morning          113413
Name: count, dtype: int64

In [137]:
# Group by 'date', 'time_category', and 'activityInference', then count occurrences
# count_per_day_time_category_activity = ActivityData.groupby(['date', 'timeCategory', 'activityInference']).size()
grouped_data = ActivityData.groupby(['date', 'timeCategory', 'activityInference']).size()

for index, count in grouped_data.items():
    print(index[0], index[1], index[2], count)

# print(count_per_day_time_category_activity)

2013-03-27 00:00:00 Early Morning 0 680
2013-03-27 00:00:00 Early Morning 1 0
2013-03-27 00:00:00 Early Morning 2 0
2013-03-27 00:00:00 Early Morning 3 0
2013-03-27 00:00:00 Morning 0 1961
2013-03-27 00:00:00 Morning 1 64
2013-03-27 00:00:00 Morning 2 0
2013-03-27 00:00:00 Morning 3 45
2013-03-27 00:00:00 Afternoon 0 1492
2013-03-27 00:00:00 Afternoon 1 385
2013-03-27 00:00:00 Afternoon 2 18
2013-03-27 00:00:00 Afternoon 3 70
2013-03-27 00:00:00 Evening 0 1265
2013-03-27 00:00:00 Evening 1 282
2013-03-27 00:00:00 Evening 2 291
2013-03-27 00:00:00 Evening 3 87
2013-03-28 00:00:00 Early Morning 0 1968
2013-03-28 00:00:00 Early Morning 1 14
2013-03-28 00:00:00 Early Morning 2 57
2013-03-28 00:00:00 Early Morning 3 15
2013-03-28 00:00:00 Morning 0 1498
2013-03-28 00:00:00 Morning 1 42
2013-03-28 00:00:00 Morning 2 0
2013-03-28 00:00:00 Morning 3 62
2013-03-28 00:00:00 Afternoon 0 1744
2013-03-28 00:00:00 Afternoon 1 146
2013-03-28 00:00:00 Afternoon 2 63
2013-03-28 00:00:00 Afternoon 3 40
2013-03-28 00:00:00 Evening 0 1739
2013-03-28 00:00:00 Evening 1 180
2013-03-28 00:00:00 Evening 2 53
2013-03-28 00:00:00 Evening 3 13
2013-03-29 00:00:00 Early Morning 0 1801
2013-03-29 00:00:00 Early Morning 1 124
2013-03-29 00:00:00 Early Morning 2 4
2013-03-29 00:00:00 Early Morning 3 67
2013-03-29 00:00:00 Morning 0 1932
2013-03-29 00:00:00 Morning 1 53
2013-03-29 00:00:00 Morning 2 5
2013-03-29 00:00:00 Morning 3 69
2013-03-29 00:00:00 Afternoon 0 1494
2013-03-29 00:00:00 Afternoon 1 334
2013-03-29 00:00:00 Afternoon 2 57
2013-03-29 00:00:00 Afternoon 3 42
2013-03-29 00:00:00 Evening 0 1455
2013-03-29 00:00:00 Evening 1 401
2013-03-29 00:00:00 Evening 2 38
2013-03-29 00:00:00 Evening 3 96
2013-03-30 00:00:00 Early Morning 0 1828
2013-03-30 00:00:00 Early Morning 1 117
2013-03-30 00:00:00 Early Morning 2 0
2013-03-30 00:00:00 Early Morning 3 67
2013-03-30 00:00:00 Morning 0 371
2013-03-30 00:00:00 Morning 1 0
2013-03-30 00:00:00 Morning 2 0
2013-03-30 00:00:00 Morning 3 0
2013-03-30 00:00:00 Afternoon 0 347
2013-03-30 00:00:00 Afternoon 1 0
2013-03-30 00:00:00 Afternoon 2 0
2013-03-30 00:00:00 Afternoon 3 0
2013-03-30 00:00:00 Evening 0 1598
2013-03-30 00:00:00 Evening 1 237
2013-03-30 00:00:00 Evening 2 32
2013-03-30 00:00:00 Evening 3 82
2013-03-31 00:00:00 Early Morning 0 1707
2013-03-31 00:00:00 Early Morning 1 184
2013-03-31 00:00:00 Early Morning 2 0
2013-03-31 00:00:00 Early Morning 3 78
2013-03-31 00:00:00 Morning 0 2083
2013-03-31 00:00:00 Morning 1 0
2013-03-31 00:00:00 Morning 2 0
2013-03-31 00:00:00 Morning 3 0
2013-03-31 00:00:00 Afternoon 0 1289
2013-03-31 00:00:00 Afternoon 1 97
2013-03-31 00:00:00 Afternoon 2 539
2013-03-31 00:00:00 Afternoon 3 70
2013-03-31 00:00:00 Evening 0 1391
2013-03-31 00:00:00 Evening 1 444
2013-03-31 00:00:00 Evening 2 73
2013-03-31 00:00:00 Evening 3 49
2013-04-01 00:00:00 Early Morning 0 2066
2013-04-01 00:00:00 Early Morning 1 0
2013-04-01 00:00:00 Early Morning 2 0
2013-04-01 00:00:00 Early Morning 3 0
2013-04-01 00:00:00 Morning 0 1946
2013-04-01 00:00:00 Morning 1 57
2013-04-01 00:00:00 Morning 2 11
2013-04-01 00:00:00 Morning 3 45
2013-04-01 00:00:00 Afternoon 0 1696
2013-04-01 00:00:00 Afternoon 1 170
2013-04-01 00:00:00 Afternoon 2 95
2013-04-01 00:00:00 Afternoon 3 17
2013-04-01 00:00:00 Evening 0 1560
2013-04-01 00:00:00 Evening 1 283
2013-04-01 00:00:00 Evening 2 9
2013-04-01 00:00:00 Evening 3 58
2013-04-02 00:00:00 Early Morning 0 2033
2013-04-02 00:00:00 Early Morning 1 20
2013-04-02 00:00:00 Early Morning 2 0
2013-04-02 00:00:00 Early Morning 3 18
2013-04-02 00:00:00 Morning 0 1958
2013-04-02 00:00:00 Morning 1 25
2013-04-02 00:00:00 Morning 2 9
2013-04-02 00:00:00 Morning 3 67
2013-04-02 00:00:00 Afternoon 0 1856
2013-04-02 00:00:00 Afternoon 1 38
2013-04-02 00:00:00 Afternoon 2 0
2013-04-02 00:00:00 Afternoon 3 49
2013-04-02 00:00:00 Evening 0 1360
2013-04-02 00:00:00 Evening 1 162
2013-04-02 00:00:00 Evening 2 250
2013-04-02 00:00:00 Evening 3 192
2013-04-03 00:00:00 Early Morning 0 1904
2013-04-03 00:00:00 Early Morning 1 29
2013-04-03 00:00:00 Early Morning 2 79
2013-04-03 00:00:00 Early Morning 3 19
2013-04-03 00:00:00 Morning 0 1946
2013-04-03 00:00:00 Morning 1 61
2013-04-03 00:00:00 Morning 2 0
2013-04-03 00:00:00 Morning 3 60
2013-04-03 00:00:00 Afternoon 0 1567
2013-04-03 00:00:00 Afternoon 1 284
2013-04-03 00:00:00 Afternoon 2 86
2013-04-03 00:00:00 Afternoon 3 35
2013-04-03 00:00:00 Evening 0 1578
2013-04-03 00:00:00 Evening 1 229
2013-04-03 00:00:00 Evening 2 48
2013-04-03 00:00:00 Evening 3 109
2013-04-04 00:00:00 Early Morning 0 2022
2013-04-04 00:00:00 Early Morning 1 22
2013-04-04 00:00:00 Early Morning 2 0
2013-04-04 00:00:00 Early Morning 3 32
2013-04-04 00:00:00 Morning 0 1968
2013-04-04 00:00:00 Morning 1 52
2013-04-04 00:00:00 Morning 2 0
2013-04-04 00:00:00 Morning 3 41
2013-04-04 00:00:00 Afternoon 0 1699
2013-04-04 00:00:00 Afternoon 1 158
2013-04-04 00:00:00 Afternoon 2 47
2013-04-04 00:00:00 Afternoon 3 73
2013-04-04 00:00:00 Evening 0 1442
2013-04-04 00:00:00 Evening 1 223
2013-04-04 00:00:00 Evening 2 160
2013-04-04 00:00:00 Evening 3 44
2013-04-05 00:00:00 Early Morning 0 1903
2013-04-05 00:00:00 Early Morning 1 23
2013-04-05 00:00:00 Early Morning 2 85
2013-04-05 00:00:00 Early Morning 3 7
2013-04-05 00:00:00 Morning 0 1973
2013-04-05 00:00:00 Morning 1 65
2013-04-05 00:00:00 Morning 2 0
2013-04-05 00:00:00 Morning 3 30
2013-04-05 00:00:00 Afternoon 0 1495
2013-04-05 00:00:00 Afternoon 1 338
2013-04-05 00:00:00 Afternoon 2 4
2013-04-05 00:00:00 Afternoon 3 62
2013-04-05 00:00:00 Evening 0 1543
2013-04-05 00:00:00 Evening 1 159
2013-04-05 00:00:00 Evening 2 62
2013-04-05 00:00:00 Evening 3 181
2013-04-06 00:00:00 Early Morning 0 1665
2013-04-06 00:00:00 Early Morning 1 80
2013-04-06 00:00:00 Early Morning 2 0
2013-04-06 00:00:00 Early Morning 3 203
2013-04-06 00:00:00 Morning 0 2085
2013-04-06 00:00:00 Morning 1 0
2013-04-06 00:00:00 Morning 2 0
2013-04-06 00:00:00 Morning 3 0
2013-04-06 00:00:00 Afternoon 0 2064
2013-04-06 00:00:00 Afternoon 1 1
2013-04-06 00:00:00 Afternoon 2 0
2013-04-06 00:00:00 Afternoon 3 5
2013-04-06 00:00:00 Evening 0 1031
2013-04-06 00:00:00 Evening 1 302
2013-04-06 00:00:00 Evening 2 226
2013-04-06 00:00:00 Evening 3 282
2013-04-07 00:00:00 Early Morning 0 1804
2013-04-07 00:00:00 Early Morning 1 96
2013-04-07 00:00:00 Early Morning 2 0
2013-04-07 00:00:00 Early Morning 3 54
2013-04-07 00:00:00 Morning 0 2085
2013-04-07 00:00:00 Morning 1 0
2013-04-07 00:00:00 Morning 2 0
2013-04-07 00:00:00 Morning 3 0
2013-04-07 00:00:00 Afternoon 0 1791
2013-04-07 00:00:00 Afternoon 1 69
2013-04-07 00:00:00 Afternoon 2 4
2013-04-07 00:00:00 Afternoon 3 18
2013-04-07 00:00:00 Evening 0 1681
2013-04-07 00:00:00 Evening 1 38
2013-04-07 00:00:00 Evening 2 285
2013-04-07 00:00:00 Evening 3 21
2013-04-08 00:00:00 Early Morning 0 2011
2013-04-08 00:00:00 Early Morning 1 9
2013-04-08 00:00:00 Early Morning 2 31
2013-04-08 00:00:00 Early Morning 3 5
2013-04-08 00:00:00 Morning 0 2006
2013-04-08 00:00:00 Morning 1 26
2013-04-08 00:00:00 Morning 2 2
2013-04-08 00:00:00 Morning 3 31
2013-04-08 00:00:00 Afternoon 0 1569
2013-04-08 00:00:00 Afternoon 1 253
2013-04-08 00:00:00 Afternoon 2 73
2013-04-08 00:00:00 Afternoon 3 67
2013-04-08 00:00:00 Evening 0 1221
2013-04-08 00:00:00 Evening 1 291
2013-04-08 00:00:00 Evening 2 394
2013-04-08 00:00:00 Evening 3 66
2013-04-09 00:00:00 Early Morning 0 2055
2013-04-09 00:00:00 Early Morning 1 3
2013-04-09 00:00:00 Early Morning 2 0
2013-04-09 00:00:00 Early Morning 3 1
2013-04-09 00:00:00 Morning 0 2076
2013-04-09 00:00:00 Morning 1 0
2013-04-09 00:00:00 Morning 2 0
2013-04-09 00:00:00 Morning 3 0
2013-04-09 00:00:00 Afternoon 0 1670
2013-04-09 00:00:00 Afternoon 1 137
2013-04-09 00:00:00 Afternoon 2 5
2013-04-09 00:00:00 Afternoon 3 150
2013-04-09 00:00:00 Evening 0 1585
2013-04-09 00:00:00 Evening 1 206
2013-04-09 00:00:00 Evening 2 13
2013-04-09 00:00:00 Evening 3 103
2013-04-10 00:00:00 Early Morning 0 2013
2013-04-10 00:00:00 Early Morning 1 13
2013-04-10 00:00:00 Early Morning 2 0
2013-04-10 00:00:00 Early Morning 3 2
2013-04-10 00:00:00 Morning 0 1990
2013-04-10 00:00:00 Morning 1 26
2013-04-10 00:00:00 Morning 2 7
2013-04-10 00:00:00 Morning 3 27
2013-04-10 00:00:00 Afternoon 0 1650
2013-04-10 00:00:00 Afternoon 1 240
2013-04-10 00:00:00 Afternoon 2 48
2013-04-10 00:00:00 Afternoon 3 43
2013-04-10 00:00:00 Evening 0 1718
2013-04-10 00:00:00 Evening 1 213
2013-04-10 00:00:00 Evening 2 2
2013-04-10 00:00:00 Evening 3 84
2013-04-11 00:00:00 Early Morning 0 2085
2013-04-11 00:00:00 Early Morning 1 0
2013-04-11 00:00:00 Early Morning 2 0
2013-04-11 00:00:00 Early Morning 3 0
2013-04-11 00:00:00 Morning 0 1946
2013-04-11 00:00:00 Morning 1 60
2013-04-11 00:00:00 Morning 2 5
2013-04-11 00:00:00 Morning 3 47
2013-04-11 00:00:00 Afternoon 0 1572
2013-04-11 00:00:00 Afternoon 1 257
2013-04-11 00:00:00 Afternoon 2 42
2013-04-11 00:00:00 Afternoon 3 83
2013-04-11 00:00:00 Evening 0 1497
2013-04-11 00:00:00 Evening 1 296
2013-04-11 00:00:00 Evening 2 55
2013-04-11 00:00:00 Evening 3 69
2013-04-12 00:00:00 Early Morning 0 1970
2013-04-12 00:00:00 Early Morning 1 1
2013-04-12 00:00:00 Early Morning 2 0
2013-04-12 00:00:00 Early Morning 3 30
2013-04-12 00:00:00 Morning 0 1987
2013-04-12 00:00:00 Morning 1 34
2013-04-12 00:00:00 Morning 2 0
2013-04-12 00:00:00 Morning 3 36
2013-04-12 00:00:00 Afternoon 0 1694
2013-04-12 00:00:00 Afternoon 1 206
2013-04-12 00:00:00 Afternoon 2 57
2013-04-12 00:00:00 Afternoon 3 23
2013-04-12 00:00:00 Evening 0 1596
2013-04-12 00:00:00 Evening 1 214
2013-04-12 00:00:00 Evening 2 20
2013-04-12 00:00:00 Evening 3 90
2013-04-13 00:00:00 Early Morning 0 2004
2013-04-13 00:00:00 Early Morning 1 31
2013-04-13 00:00:00 Early Morning 2 5
2013-04-13 00:00:00 Early Morning 3 20
2013-04-13 00:00:00 Morning 0 2082
2013-04-13 00:00:00 Morning 1 0
2013-04-13 00:00:00 Morning 2 0
2013-04-13 00:00:00 Morning 3 0
2013-04-13 00:00:00 Afternoon 0 2032
2013-04-13 00:00:00 Afternoon 1 12
2013-04-13 00:00:00 Afternoon 2 0
2013-04-13 00:00:00 Afternoon 3 17
2013-04-13 00:00:00 Evening 0 1626
2013-04-13 00:00:00 Evening 1 65
2013-04-13 00:00:00 Evening 2 12
2013-04-13 00:00:00 Evening 3 316
2013-04-14 00:00:00 Early Morning 0 2030
2013-04-14 00:00:00 Early Morning 1 30
2013-04-14 00:00:00 Early Morning 2 0
2013-04-14 00:00:00 Early Morning 3 15
2013-04-14 00:00:00 Morning 0 2082
2013-04-14 00:00:00 Morning 1 0
2013-04-14 00:00:00 Morning 2 0
2013-04-14 00:00:00 Morning 3 0
2013-04-14 00:00:00 Afternoon 0 1957
2013-04-14 00:00:00 Afternoon 1 19
2013-04-14 00:00:00 Afternoon 2 0
2013-04-14 00:00:00 Afternoon 3 30
2013-04-14 00:00:00 Evening 0 1881
2013-04-14 00:00:00 Evening 1 13
2013-04-14 00:00:00 Evening 2 160
2013-04-14 00:00:00 Evening 3 13
2013-04-15 00:00:00 Early Morning 0 1868
2013-04-15 00:00:00 Early Morning 1 8
2013-04-15 00:00:00 Early Morning 2 166
2013-04-15 00:00:00 Early Morning 3 6
2013-04-15 00:00:00 Morning 0 1984
2013-04-15 00:00:00 Morning 1 52
2013-04-15 00:00:00 Morning 2 3
2013-04-15 00:00:00 Morning 3 20
2013-04-15 00:00:00 Afternoon 0 1566
2013-04-15 00:00:00 Afternoon 1 253
2013-04-15 00:00:00 Afternoon 2 44
2013-04-15 00:00:00 Afternoon 3 71
2013-04-15 00:00:00 Evening 0 1626
2013-04-15 00:00:00 Evening 1 224
2013-04-15 00:00:00 Evening 2 0
2013-04-15 00:00:00 Evening 3 88
2013-04-16 00:00:00 Early Morning 0 2053
2013-04-16 00:00:00 Early Morning 1 4
2013-04-16 00:00:00 Early Morning 2 0
2013-04-16 00:00:00 Early Morning 3 3
2013-04-16 00:00:00 Morning 0 2011
2013-04-16 00:00:00 Morning 1 27
2013-04-16 00:00:00 Morning 2 0
2013-04-16 00:00:00 Morning 3 9
2013-04-16 00:00:00 Afternoon 0 1797
2013-04-16 00:00:00 Afternoon 1 116
2013-04-16 00:00:00 Afternoon 2 19
2013-04-16 00:00:00 Afternoon 3 71
2013-04-16 00:00:00 Evening 0 1572
2013-04-16 00:00:00 Evening 1 123
2013-04-16 00:00:00 Evening 2 0
2013-04-16 00:00:00 Evening 3 42
2013-04-17 00:00:00 Early Morning 0 2058
2013-04-17 00:00:00 Early Morning 1 8
2013-04-17 00:00:00 Early Morning 2 0
2013-04-17 00:00:00 Early Morning 3 0
2013-04-17 00:00:00 Morning 0 1962
2013-04-17 00:00:00 Morning 1 20
2013-04-17 00:00:00 Morning 2 8
2013-04-17 00:00:00 Morning 3 55
2013-04-17 00:00:00 Afternoon 0 1532
2013-04-17 00:00:00 Afternoon 1 340
2013-04-17 00:00:00 Afternoon 2 59
2013-04-17 00:00:00 Afternoon 3 22
2013-04-17 00:00:00 Evening 0 1525
2013-04-17 00:00:00 Evening 1 316
2013-04-17 00:00:00 Evening 2 50
2013-04-17 00:00:00 Evening 3 42
2013-04-18 00:00:00 Early Morning 0 2021
2013-04-18 00:00:00 Early Morning 1 16
2013-04-18 00:00:00 Early Morning 2 0
2013-04-18 00:00:00 Early Morning 3 24
2013-04-18 00:00:00 Morning 0 2004
2013-04-18 00:00:00 Morning 1 12
2013-04-18 00:00:00 Morning 2 0
2013-04-18 00:00:00 Morning 3 55
2013-04-18 00:00:00 Afternoon 0 1833
2013-04-18 00:00:00 Afternoon 1 97
2013-04-18 00:00:00 Afternoon 2 62
2013-04-18 00:00:00 Afternoon 3 39
2013-04-18 00:00:00 Evening 0 1763
2013-04-18 00:00:00 Evening 1 137
2013-04-18 00:00:00 Evening 2 18
2013-04-18 00:00:00 Evening 3 36
2013-04-19 00:00:00 Early Morning 0 1941
2013-04-19 00:00:00 Early Morning 1 29
2013-04-19 00:00:00 Early Morning 2 5
2013-04-19 00:00:00 Early Morning 3 38
2013-04-19 00:00:00 Morning 0 2055
2013-04-19 00:00:00 Morning 1 11
2013-04-19 00:00:00 Morning 2 0
2013-04-19 00:00:00 Morning 3 0
2013-04-19 00:00:00 Afternoon 0 1458
2013-04-19 00:00:00 Afternoon 1 319
2013-04-19 00:00:00 Afternoon 2 107
2013-04-19 00:00:00 Afternoon 3 79
2013-04-19 00:00:00 Evening 0 698
2013-04-19 00:00:00 Evening 1 333
2013-04-19 00:00:00 Evening 2 11
2013-04-19 00:00:00 Evening 3 902
2013-04-20 00:00:00 Early Morning 0 660
2013-04-20 00:00:00 Early Morning 1 0
2013-04-20 00:00:00 Early Morning 2 0
2013-04-20 00:00:00 Early Morning 3 9
2013-04-20 00:00:00 Morning 0 2085
2013-04-20 00:00:00 Morning 1 0
2013-04-20 00:00:00 Morning 2 0
2013-04-20 00:00:00 Morning 3 0
2013-04-20 00:00:00 Afternoon 0 1640
2013-04-20 00:00:00 Afternoon 1 206
2013-04-20 00:00:00 Afternoon 2 11
2013-04-20 00:00:00 Afternoon 3 141
2013-04-20 00:00:00 Evening 0 721
2013-04-20 00:00:00 Evening 1 376
2013-04-20 00:00:00 Evening 2 147
2013-04-20 00:00:00 Evening 3 770
2013-04-21 00:00:00 Early Morning 0 1737
2013-04-21 00:00:00 Early Morning 1 50
2013-04-21 00:00:00 Early Morning 2 3
2013-04-21 00:00:00 Early Morning 3 254
2013-04-21 00:00:00 Morning 0 2084
2013-04-21 00:00:00 Morning 1 0
2013-04-21 00:00:00 Morning 2 0
2013-04-21 00:00:00 Morning 3 0
2013-04-21 00:00:00 Afternoon 0 2011
2013-04-21 00:00:00 Afternoon 1 26
2013-04-21 00:00:00 Afternoon 2 0
2013-04-21 00:00:00 Afternoon 3 8
2013-04-21 00:00:00 Evening 0 1851
2013-04-21 00:00:00 Evening 1 0
2013-04-21 00:00:00 Evening 2 207
2013-04-21 00:00:00 Evening 3 2
2013-04-22 00:00:00 Early Morning 0 1838
2013-04-22 00:00:00 Early Morning 1 60
2013-04-22 00:00:00 Early Morning 2 80
2013-04-22 00:00:00 Early Morning 3 28
2013-04-22 00:00:00 Morning 0 1939
2013-04-22 00:00:00 Morning 1 42
2013-04-22 00:00:00 Morning 2 0
2013-04-22 00:00:00 Morning 3 49
2013-04-22 00:00:00 Afternoon 0 1567
2013-04-22 00:00:00 Afternoon 1 351
2013-04-22 00:00:00 Afternoon 2 1
2013-04-22 00:00:00 Afternoon 3 37
2013-04-22 00:00:00 Evening 0 1300
2013-04-22 00:00:00 Evening 1 193
2013-04-22 00:00:00 Evening 2 0
2013-04-22 00:00:00 Evening 3 53
2013-04-23 00:00:00 Early Morning 0 1977
2013-04-23 00:00:00 Early Morning 1 15
2013-04-23 00:00:00 Early Morning 2 0
2013-04-23 00:00:00 Early Morning 3 60
2013-04-23 00:00:00 Morning 0 1980
2013-04-23 00:00:00 Morning 1 35
2013-04-23 00:00:00 Morning 2 0
2013-04-23 00:00:00 Morning 3 54
2013-04-23 00:00:00 Afternoon 0 1687
2013-04-23 00:00:00 Afternoon 1 137
2013-04-23 00:00:00 Afternoon 2 19
2013-04-23 00:00:00 Afternoon 3 140
2013-04-23 00:00:00 Evening 0 1733
2013-04-23 00:00:00 Evening 1 148
2013-04-23 00:00:00 Evening 2 9
2013-04-23 00:00:00 Evening 3 81
2013-04-24 00:00:00 Early Morning 0 1759
2013-04-24 00:00:00 Early Morning 1 78
2013-04-24 00:00:00 Early Morning 2 4
2013-04-24 00:00:00 Early Morning 3 136
2013-04-24 00:00:00 Morning 0 2085
2013-04-24 00:00:00 Morning 1 0
2013-04-24 00:00:00 Morning 2 0
2013-04-24 00:00:00 Morning 3 0
2013-04-24 00:00:00 Afternoon 0 1694
2013-04-24 00:00:00 Afternoon 1 174
2013-04-24 00:00:00 Afternoon 2 31
2013-04-24 00:00:00 Afternoon 3 73
2013-04-24 00:00:00 Evening 0 1578
2013-04-24 00:00:00 Evening 1 15
2013-04-24 00:00:00 Evening 2 0
2013-04-24 00:00:00 Evening 3 13
2013-04-25 00:00:00 Early Morning 0 2058
2013-04-25 00:00:00 Early Morning 1 0
2013-04-25 00:00:00 Early Morning 2 0
2013-04-25 00:00:00 Early Morning 3 0
2013-04-25 00:00:00 Morning 0 1943
2013-04-25 00:00:00 Morning 1 55
2013-04-25 00:00:00 Morning 2 0
2013-04-25 00:00:00 Morning 3 40
2013-04-25 00:00:00 Afternoon 0 1752
2013-04-25 00:00:00 Afternoon 1 184
2013-04-25 00:00:00 Afternoon 2 8
2013-04-25 00:00:00 Afternoon 3 49
2013-04-25 00:00:00 Evening 0 1517
2013-04-25 00:00:00 Evening 1 319
2013-04-25 00:00:00 Evening 2 33
2013-04-25 00:00:00 Evening 3 75
2013-04-26 00:00:00 Early Morning 0 2051
2013-04-26 00:00:00 Early Morning 1 2
2013-04-26 00:00:00 Early Morning 2 0
2013-04-26 00:00:00 Early Morning 3 0
2013-04-26 00:00:00 Morning 0 1964
2013-04-26 00:00:00 Morning 1 22
2013-04-26 00:00:00 Morning 2 2
2013-04-26 00:00:00 Morning 3 69
2013-04-26 00:00:00 Afternoon 0 1619
2013-04-26 00:00:00 Afternoon 1 268
2013-04-26 00:00:00 Afternoon 2 60
2013-04-26 00:00:00 Afternoon 3 33
2013-04-26 00:00:00 Evening 0 1553
2013-04-26 00:00:00 Evening 1 260
2013-04-26 00:00:00 Evening 2 12
2013-04-26 00:00:00 Evening 3 46
2013-04-27 00:00:00 Early Morning 0 1890
2013-04-27 00:00:00 Early Morning 1 115
2013-04-27 00:00:00 Early Morning 2 1
2013-04-27 00:00:00 Early Morning 3 45
2013-04-27 00:00:00 Morning 0 2079
2013-04-27 00:00:00 Morning 1 0
2013-04-27 00:00:00 Morning 2 0
2013-04-27 00:00:00 Morning 3 0
2013-04-27 00:00:00 Afternoon 0 1620
2013-04-27 00:00:00 Afternoon 1 40
2013-04-27 00:00:00 Afternoon 2 395
2013-04-27 00:00:00 Afternoon 3 10
2013-04-27 00:00:00 Evening 0 1024
2013-04-27 00:00:00 Evening 1 175
2013-04-27 00:00:00 Evening 2 531
2013-04-27 00:00:00 Evening 3 223
2013-04-28 00:00:00 Early Morning 0 583
2013-04-28 00:00:00 Early Morning 1 92
2013-04-28 00:00:00 Early Morning 2 0
2013-04-28 00:00:00 Early Morning 3 161
2013-04-28 00:00:00 Morning 0 0
2013-04-28 00:00:00 Morning 1 0
2013-04-28 00:00:00 Morning 2 0
2013-04-28 00:00:00 Morning 3 0
2013-04-28 00:00:00 Afternoon 0 2006
2013-04-28 00:00:00 Afternoon 1 19
2013-04-28 00:00:00 Afternoon 2 0
2013-04-28 00:00:00 Afternoon 3 0
2013-04-28 00:00:00 Evening 0 1418
2013-04-28 00:00:00 Evening 1 178
2013-04-28 00:00:00 Evening 2 331
2013-04-28 00:00:00 Evening 3 84
2013-04-29 00:00:00 Early Morning 0 1880
2013-04-29 00:00:00 Early Morning 1 56
2013-04-29 00:00:00 Early Morning 2 7
2013-04-29 00:00:00 Early Morning 3 60
2013-04-29 00:00:00 Morning 0 1910
2013-04-29 00:00:00 Morning 1 38
2013-04-29 00:00:00 Morning 2 0
2013-04-29 00:00:00 Morning 3 74
2013-04-29 00:00:00 Afternoon 0 1534
2013-04-29 00:00:00 Afternoon 1 275
2013-04-29 00:00:00 Afternoon 2 42
2013-04-29 00:00:00 Afternoon 3 52
2013-04-29 00:00:00 Evening 0 1595
2013-04-29 00:00:00 Evening 1 221
2013-04-29 00:00:00 Evening 2 18
2013-04-29 00:00:00 Evening 3 17
2013-04-30 00:00:00 Early Morning 0 1937
2013-04-30 00:00:00 Early Morning 1 36
2013-04-30 00:00:00 Early Morning 2 10
2013-04-30 00:00:00 Early Morning 3 53
2013-04-30 00:00:00 Morning 0 1961
2013-04-30 00:00:00 Morning 1 48
2013-04-30 00:00:00 Morning 2 0
2013-04-30 00:00:00 Morning 3 34
2013-04-30 00:00:00 Afternoon 0 969
2013-04-30 00:00:00 Afternoon 1 49
2013-04-30 00:00:00 Afternoon 2 0
2013-04-30 00:00:00 Afternoon 3 29
2013-04-30 00:00:00 Evening 0 1349
2013-04-30 00:00:00 Evening 1 159
2013-04-30 00:00:00 Evening 2 33
2013-04-30 00:00:00 Evening 3 29
2013-05-01 00:00:00 Early Morning 0 1881
2013-05-01 00:00:00 Early Morning 1 73
2013-05-01 00:00:00 Early Morning 2 0
2013-05-01 00:00:00 Early Morning 3 63

/var/folders/__/2j137gs56_s_11dyhp8v1q_w0000gn/T/ipykernel_50257/4211473134.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped_data = ActivityData.groupby(['date', 'timeCategory', 'activityInference']).size()

In [125]:
print(result_df.keys())
result_df = result_df.drop(columns=['index'])
print(result_df.keys())

Index(['index', 'userId', 'Early Morning0', 'Early Morning1', 'Early Morning2',
       'Early Morning3', 'Morning0', 'Morning1', 'Morning2', 'Morning3',
       'Afternoon0', 'Afternoon1', 'Afternoon2', 'Afternoon3', 'Evening0',
       'Evening1', 'Evening2', 'Evening3'],
      dtype='object')
Index(['userId', 'Early Morning0', 'Early Morning1', 'Early Morning2',
       'Early Morning3', 'Morning0', 'Morning1', 'Morning2', 'Morning3',
       'Afternoon0', 'Afternoon1', 'Afternoon2', 'Afternoon3', 'Evening0',
       'Evening1', 'Evening2', 'Evening3'],
      dtype='object')

In [138]:
grouped_data_week = ActivityData.groupby(['week', 'timeCategory', 'activityInference']).size()

for index, count in grouped_data_week.items():
    print(index[0], index[1], index[2], count)

13 Early Morning 0 7984
13 Early Morning 1 439
13 Early Morning 2 61
13 Early Morning 3 227
13 Morning 0 7845
13 Morning 1 159
13 Morning 2 5
13 Morning 3 176
13 Afternoon 0 6366
13 Afternoon 1 962
13 Afternoon 2 677
13 Afternoon 3 222
13 Evening 0 7448
13 Evening 1 1544
13 Evening 2 487
13 Evening 3 327
14 Early Morning 0 13397
14 Early Morning 1 270
14 Early Morning 2 164
14 Early Morning 3 333
14 Morning 0 13961
14 Morning 1 260
14 Morning 2 20
14 Morning 3 243
14 Afternoon 0 12168
14 Afternoon 1 1058
14 Afternoon 2 236
14 Afternoon 3 259
14 Evening 0 10195
14 Evening 1 1396
14 Evening 2 1040
14 Evening 3 887
15 Early Morning 0 14168
15 Early Morning 1 87
15 Early Morning 2 36
15 Early Morning 3 73
15 Morning 0 14169
15 Morning 1 146
15 Morning 2 14
15 Morning 3 141
15 Afternoon 0 12144
15 Afternoon 1 1124
15 Afternoon 2 225
15 Afternoon 3 413
15 Evening 0 11124
15 Evening 1 1298
15 Evening 2 656
15 Evening 3 741
16 Early Morning 0 12338
16 Early Morning 1 115
16 Early Morning 2 174
16 Early Morning 3 334
16 Morning 0 14185
16 Morning 1 122
16 Morning 2 11
16 Morning 3 139
16 Afternoon 0 11837
16 Afternoon 1 1357
16 Afternoon 2 302
16 Afternoon 3 431
16 Evening 0 9756
16 Evening 1 1509
16 Evening 2 433
16 Evening 3 1882
17 Early Morning 0 12156
17 Early Morning 1 362
17 Early Morning 2 85
17 Early Morning 3 430
17 Morning 0 11990
17 Morning 1 154
17 Morning 2 2
17 Morning 3 212
17 Afternoon 0 11945
17 Afternoon 1 1173
17 Afternoon 2 514
17 Afternoon 3 342
17 Evening 0 10123
17 Evening 1 1288
17 Evening 2 916
17 Evening 3 575
18 Early Morning 0 11971
18 Early Morning 1 211
18 Early Morning 2 17
18 Early Morning 3 224
18 Morning 0 9845
18 Morning 1 1772
18 Morning 2 203
18 Morning 3 447
18 Afternoon 0 6495
18 Afternoon 1 2050
18 Afternoon 2 449
18 Afternoon 3 394
18 Evening 0 8766
18 Evening 1 1226
18 Evening 2 128
18 Evening 3 951
19 Early Morning 0 12716
19 Early Morning 1 217
19 Early Morning 2 26
19 Early Morning 3 551
19 Morning 0 12091
19 Morning 1 867
19 Morning 2 397
19 Morning 3 170
19 Afternoon 0 10442
19 Afternoon 1 1840
19 Afternoon 2 276
19 Afternoon 3 1069
19 Evening 0 11601
19 Evening 1 1233
19 Evening 2 164
19 Evening 3 923
20 Early Morning 0 12010
20 Early Morning 1 165
20 Early Morning 2 26
20 Early Morning 3 191
20 Morning 0 9867
20 Morning 1 229
20 Morning 2 11
20 Morning 3 236
20 Afternoon 0 7600
20 Afternoon 1 665
20 Afternoon 2 85
20 Afternoon 3 1024
20 Evening 0 8117
20 Evening 1 1424
20 Evening 2 141
20 Evening 3 1507
21 Early Morning 0 7643
21 Early Morning 1 111
21 Early Morning 2 6
21 Early Morning 3 189
21 Morning 0 6377
21 Morning 1 4
21 Morning 2 0
21 Morning 3 0
21 Afternoon 0 8098
21 Afternoon 1 614
21 Afternoon 2 6
21 Afternoon 3 944
21 Evening 0 5605
21 Evening 1 934
21 Evening 2 110
21 Evening 3 342
22 Early Morning 0 8756
22 Early Morning 1 144
22 Early Morning 2 22
22 Early Morning 3 156
22 Morning 0 6769
22 Morning 1 80
22 Morning 2 17
22 Morning 3 77
22 Afternoon 0 6545
22 Afternoon 1 739
22 Afternoon 2 613
22 Afternoon 3 328
22 Evening 0 6848
22 Evening 1 1311
22 Evening 2 235
22 Evening 3 771

/var/folders/__/2j137gs56_s_11dyhp8v1q_w0000gn/T/ipykernel_50257/2974496904.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grouped_data_week = ActivityData.groupby(['week', 'timeCategory', 'activityInference']).size()